version: "3"
services:
  php:
    # імʼя контейнеру, яке будемо використовувати при вході на контейнер
    container_name: avrys_php-pro
    build:
      context: ./
      # посилання на докерфайл з налаштуванням контейнеру
      dockerfile: "docker/configs/php/Dockerfile"
    # встановлюємо змінні оточення
    environment:
      XDEBUG_CONFIG: "remote_host={{YOUR_IP_ADDRESS}}"
      PHP_IDE_CONFIG: "serverName=docker"
    # прописуємо синхронізацію директорій
    volumes:
      - ./:/srv/src/php-pro
    links:
      - db_mysql

  db_mysql:
    image: mysql:latest
    container_name: php-pro_mysql
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: php_pro
      MYSQL_USER: avrys
      MYSQL_PASSWORD: mysqlavrys
    volumes:
      - ./docker/databases/mysql_dump:/docker-entrypoint-initdb.d
#      - ./mysql_data:/var/lib/mysql
